spring.application.name=SmartParkingBackend

# Cấu hình Server
server.port=8080

# Cấu hình Database (Tạm thời để trống hoặc điền bừa để ko lỗi start)
spring.datasource.url=jdbc:mysql://localhost:3306/smartparking_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Tắt security mặc định để đỡ phải đăng nhập lúc test
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration